# Generated by Django 6.0.5 on 2026-05-21 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LabelFormat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('width', models.CharField(help_text='e.g. 3.5in or 90mm', max_length=20)),
                ('height', models.CharField(help_text='e.g. 1.1in or 29mm', max_length=20)),
                ('is_default', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Label Format',
                'verbose_name_plural': 'Label Formats',
                'ordering': ['name'],
            },
        ),
    ]
