# Generated by Django 6.0.5 on 2026-06-29 17:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_labelformat'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manufacturer', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Item Model',
                'verbose_name_plural': 'Item Models',
                'ordering': ['manufacturer', 'name'],
                'unique_together': {('manufacturer', 'name')},
            },
        ),
        migrations.AddField(
            model_name='item',
            name='item_model',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items', to='inventory.itemmodel'),
        ),
    ]
