# Generated by Django 6.0.5 on 2026-06-29 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_add_item_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemmodel',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
