# Generated by Django 6.0.5 on 2026-06-29 19:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_add_itemmodel_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemmodel',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='item_models', to='inventory.category'),
        ),
    ]
